### ISSUE TITLE
Add hooks for server teardown

### ISSUE THREAD

**Issue by simonauner** [playwright-community/jest-playwright#609]
**Is your feature request related to a problem? Please describe.**
Not really, we manage a workaround with docker-compose for now.

**Describe the solution you'd like**
I would like to be able to run a server (https://github.com/playwright-community/jest-playwright#start-a-server) as a docker image. I got the tests running by specifying 
```
command: "docker run ${IMAGE}:${TAG} -p 3000:3000"
```

But jest-playwright isn't able to stop the process after the tests are done with the message
```
Jest did not exit one second after the test run has completed.
```

If possible I would like to have a `tearDownServer` option where I could kill off the docker processes myself.

**Describe alternatives you've considered**
I've tried to include the setup objects from https://github.com/playwright-community/jest-process-manager but didn't understand how they would cooperate with `jest-playwright.config.js`. Maybe it's just me being confused over configuration setup?

**Comment by simonauner** [comment]
If anyone else stumbles this problem, which is "I want to run the server as a docker container", here's our current workaround.

*package.json*
```json
{
    "name": "ui-tests",
    "version": "1.0.0",
    "description": "",
    "scripts": {
        "test": "jest || true",
        "posttest": "docker ps | grep '<insert name of your application image>' | awk '{ print $1 }' | xargs docker stop",
    },
    "author": "",
    "license": "ISC",
    "dependencies": {
        "jest": "^26.6.3",
        "jest-playwright-preset": "^1.4.7",
        "playwright": "^1.9.1"
    },
    "jest": {
        "preset": "jest-playwright-preset"
    },
    "devDependencies": {}
}
```

*jest-playwright-config.js*
```javascript
module.exports = {
    serverOptions: {
        command: `docker run --env-file=../.dockerenv -a STDIN -p 3001:3000 ${image}:${tag}`,
        port: 3001,
    },
};
```

`-a STDIN` prevents the `Jest did not exit one second after the test run has completed.` message from showing up and actually stops the test run after it has completed.

The `posttest` npm task finds the image that was started and shuts it down.
This has been found working in Azure pipelines vmImage `ubuntu-18.04` as well:
```yaml
jobs:
    - job: build
      # ... builds and publishes a docker image to ACR (<insert name of your ACR>.azurecr.io/<insert name of your application image>:$(Build.BuildNumber))
    - job: ui_tests
      displayName: "UI tests"
      dependsOn: build
      variables:
        dockerRegistryServiceConnection: "<insert ID of service connection>"
        containerRegistry: "<insert name of your ACR>.azurecr.io"
        microserviceName: '<insert name of your application image>'
      pool:
          vmImage: "ubuntu-18.04"
      steps:
        - task: Docker@2
          displayName: Login to ACR
          inputs:
            command: login
            containerRegistry: ${{ variables.dockerRegistryServiceConnection }}
        - bash: |
            npm install
          displayName: npm install
        - bash: |
            npm test
          displayName: Run tests
          env:
            IMAGE: ${{ variables.containerRegistry }}/${{ variables.applicationname }}
            TAG: $(Build.BuildNumber)

```
